# -*- coding: utf-8 -*-
"""01_extract_pulsar_positions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""



"""
Extract pulsar ecliptic coordinates from NANOGrav .par files.

Output:
    pulsar_positions.csv
"""

import pandas as pd

from config import PAR_DIR, OUTPUT_DIR


def read_par_file(path):
    """Extract PSR, ELONG, and ELAT from one timing-model file."""

    pulsar = None
    elong = None
    elat = None

    with open(path, "r") as f:
        for line in f:
            parts = line.split()

            if len(parts) < 2:
                continue

            keyword = parts[0]

            if keyword == "PSR":
                pulsar = parts[1]

            elif keyword == "ELONG":
                elong = float(parts[1])

            elif keyword == "ELAT":
                elat = float(parts[1])

    return pulsar, elong, elat


def main():

    rows = []

    for path in sorted(PAR_DIR.glob("*.par")):

        pulsar, elong, elat = read_par_file(path)

        if pulsar is None:
            continue

        if elong is None or elat is None:
            continue

        rows.append(
            {
                "pulsar": pulsar,
                "ecliptic_longitude_deg": elong % 360.0,
                "ecliptic_latitude_deg": elat,
            }
        )

    df = pd.DataFrame(rows)

    df = (
        df.drop_duplicates(subset="pulsar")
        .sort_values("pulsar")
        .reset_index(drop=True)
    )

    output = OUTPUT_DIR / "pulsar_positions.csv"

    df.to_csv(output, index=False)

    print("Pulsars found:", len(df))
    print("Saved:", output)


if __name__ == "__main__":
    main()