# -*- coding: utf-8 -*-
"""02_compute_pair_separations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Calculate angular separations between all unique pulsar pairs.

Output:
    pair_separations.csv
"""

import numpy as np
import pandas as pd

from config import OUTPUT_DIR


def angular_separation(lon1, lat1, lon2, lat2):
    """
    Calculate spherical angular separation in degrees.
    """

    lon1 = np.radians(lon1)
    lat1 = np.radians(lat1)
    lon2 = np.radians(lon2)
    lat2 = np.radians(lat2)

    cos_theta = (
        np.sin(lat1) * np.sin(lat2)
        + np.cos(lat1)
        * np.cos(lat2)
        * np.cos(lon1 - lon2)
    )

    cos_theta = np.clip(cos_theta, -1.0, 1.0)

    return np.degrees(np.arccos(cos_theta))


def main():

    positions = pd.read_csv(
        OUTPUT_DIR / "pulsar_positions.csv"
    )

    rows = []

    for i in range(len(positions)):

        for j in range(i + 1, len(positions)):

            p1 = positions.iloc[i]
            p2 = positions.iloc[j]

            separation = angular_separation(
                p1["ecliptic_longitude_deg"],
                p1["ecliptic_latitude_deg"],
                p2["ecliptic_longitude_deg"],
                p2["ecliptic_latitude_deg"],
            )

            rows.append(
                {
                    "pulsar1": p1["pulsar"],
                    "pulsar2": p2["pulsar"],
                    "separation_deg": separation,
                }
            )

    df = pd.DataFrame(rows)

    output = OUTPUT_DIR / "pair_separations.csv"

    df.to_csv(output, index=False)

    print("Pulsars:", len(positions))
    print("Unique pairs:", len(df))
    print("Saved:", output)


if __name__ == "__main__":
    main()