# -*- coding: utf-8 -*-
"""03_rms_whitening_analysis.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Compare original and published-whitened residual RMS.

For a 5-column .avg.res file:

    column 0 = MJD
    column 1 = observing frequency
    column 2 = original residual
    column 3 = whitened residual
    column 4 = uncertainty

Output:
    rms_whitening_results.csv
"""

import numpy as np
import pandas as pd

from config import RESIDUAL_DIR, OUTPUT_DIR


def calculate_rms(values):
    """Calculate root-mean-square."""

    return np.sqrt(np.mean(values ** 2))


def main():

    rows = []

    files = sorted(
        RESIDUAL_DIR.glob("*_NG15yr_nb.avg.res")
    )

    for path in files:

        try:
            data = np.loadtxt(path)
        except Exception:
            continue

        # We need original + whitened residuals.
        if data.ndim != 2 or data.shape[1] < 5:
            continue

        pulsar = path.name.replace(
            "_NG15yr_nb.avg.res",
            ""
        )

        original = data[:, 2]
        whitened = data[:, 3]

        original_rms = calculate_rms(original)
        whitened_rms = calculate_rms(whitened)

        reduction = (
            100.0
            * (1.0 - whitened_rms / original_rms)
        )

        rows.append(
            {
                "pulsar": pulsar,
                "n_observations": len(data),
                "original_rms_seconds": original_rms,
                "whitened_rms_seconds": whitened_rms,
                "original_rms_us": original_rms * 1e6,
                "whitened_rms_us": whitened_rms * 1e6,
                "rms_reduction_percent": reduction,
            }
        )

    df = pd.DataFrame(rows)

    df = df.sort_values(
        "rms_reduction_percent",
        ascending=False
    ).reset_index(drop=True)

    output = OUTPUT_DIR / "rms_whitening_results.csv"

    df.to_csv(output, index=False)

    print("Pulsars with original + whitened products:", len(df))
    print()
    print(
        df[
            [
                "pulsar",
                "original_rms_us",
                "whitened_rms_us",
                "rms_reduction_percent",
            ]
        ].to_string(index=False)
    )

    print()
    print("Saved:", output)


if __name__ == "__main__":
    main()