# -*- coding: utf-8 -*-
"""04_define_selection_groups.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Define exploratory pulsar-selection groups based on RMS reduction.

Strong:
    RMS reduction > 50%

Moderate:
    RMS reduction >= 10% and <= 50%

Weak:
    RMS reduction < 10%

These thresholds are exploratory and are not official NANOGrav
classifications.

Output:
    pulsar_selection_groups.csv
"""

import pandas as pd

from config import (
    OUTPUT_DIR,
    STRONG_THRESHOLD,
    MODERATE_THRESHOLD,
)


def assign_group(reduction):

    if reduction > STRONG_THRESHOLD:
        return "Strong"

    elif reduction >= MODERATE_THRESHOLD:
        return "Moderate"

    else:
        return "Weak"


def main():

    path = OUTPUT_DIR / "rms_whitening_results.csv"

    df = pd.read_csv(path)

    df["group"] = df["rms_reduction_percent"].apply(
        assign_group
    )

    output = OUTPUT_DIR / "pulsar_selection_groups.csv"

    df.to_csv(output, index=False)

    print("Pulsars by selection group:")
    print(df["group"].value_counts())

    print()
    print("Saved:", output)


if __name__ == "__main__":
    main()