# -*- coding: utf-8 -*-
"""05_pairwise_correlations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Calculate pairwise Pearson correlations using one-to-one nearest-time
matching.

This is an exploratory statistic and is NOT the full PTA
Hellings-Downs estimator.

Outputs:

    selection_group_correlations.csv
    ten_pulsar_pair_correlations.csv
"""

from itertools import combinations

import numpy as np
import pandas as pd

from config import (
    OUTPUT_DIR,
    RESIDUAL_DIR,
    MAX_MATCH_DAYS,
    TEN_PULSARS,
)


def load_residuals(pulsar):

    path = (
        RESIDUAL_DIR
        / f"{pulsar}_NG15yr_nb.avg.res"
    )

    data = np.loadtxt(path)

    if data.ndim != 2 or data.shape[1] < 5:
        raise ValueError(
            f"{pulsar} does not contain a whitened residual column."
        )

    return data[:, 0], data[:, 2], data[:, 3]


def one_to_one_match(t1, t2, max_days):

    used = set()
    matches = []

    for i in range(len(t1)):

        distances = np.abs(t2 - t1[i])

        for j in np.argsort(distances):

            if j in used:
                continue

            if distances[j] <= max_days:
                matches.append((i, j))
                used.add(j)
                break

    return matches


def calculate_pair(p1, p2):

    t1, r1, w1 = load_residuals(p1)
    t2, r2, w2 = load_residuals(p2)

    matches = one_to_one_match(
        t1,
        t2,
        MAX_MATCH_DAYS,
    )

    if len(matches) < 3:
        return None

    original_1 = np.array(
        [r1[i] for i, j in matches]
    )

    original_2 = np.array(
        [r2[j] for i, j in matches]
    )

    white_1 = np.array(
        [w1[i] for i, j in matches]
    )

    white_2 = np.array(
        [w2[j] for i, j in matches]
    )

    original_corr = np.corrcoef(
        original_1,
        original_2
    )[0, 1]

    white_corr = np.corrcoef(
        white_1,
        white_2
    )[0, 1]

    return {
        "pulsar1": p1,
        "pulsar2": p2,
        "matched_pairs": len(matches),
        "original_correlation": original_corr,
        "white_correlation": white_corr,
    }


def add_separations(df):

    separation_file = (
        OUTPUT_DIR / "pair_separations.csv"
    )

    separations = pd.read_csv(separation_file)

    merged = df.merge(
        separations,
        on=["pulsar1", "pulsar2"],
        how="left",
    )

    reverse = merged["separation_deg"].isna()

    if reverse.any():

        reverse_df = df.loc[reverse].copy()

        reverse_df = reverse_df.rename(
            columns={
                "pulsar1": "pulsar2",
                "pulsar2": "pulsar1",
            }
        )

        reverse_df = reverse_df.merge(
            separations,
            on=["pulsar1", "pulsar2"],
            how="left",
        )

        merged.loc[
            reverse,
            "separation_deg"
        ] = reverse_df["separation_deg"].values

    return merged


def calculate_pairs(pulsars):

    rows = []

    for p1, p2 in combinations(pulsars, 2):

        try:
            result = calculate_pair(p1, p2)
        except Exception as error:
            print(
                f"Skipping {p1} / {p2}: {error}"
            )
            continue

        if result is not None:
            rows.append(result)

    if not rows:
        return pd.DataFrame()

    return pd.DataFrame(rows)


def main():

    groups = pd.read_csv(
        OUTPUT_DIR / "pulsar_selection_groups.csv"
    )

    all_group_results = []

    for group_name in [
        "Strong",
        "Moderate",
        "Weak",
    ]:

        pulsars = groups.loc[
            groups["group"] == group_name,
            "pulsar",
        ].tolist()

        print()
        print("=" * 60)
        print(group_name)
        print("Pulsars:", len(pulsars))
        print("=" * 60)

        result = calculate_pairs(pulsars)

        if result.empty:
            continue

        result["group"] = group_name

        all_group_results.append(result)

        print("Pairs calculated:", len(result))

    group_df = pd.concat(
        all_group_results,
        ignore_index=True,
    )

    group_df = add_separations(group_df)

    group_output = (
        OUTPUT_DIR
        / "selection_group_correlations.csv"
    )

    group_df.to_csv(
        group_output,
        index=False,
    )

    # -------------------------------------------------
    # 10-pulsar analysis
    # -------------------------------------------------

    print()
    print("=" * 60)
    print("10-PULSAR ANALYSIS")
    print("=" * 60)

    ten_df = calculate_pairs(TEN_PULSARS)

    ten_df = add_separations(ten_df)

    ten_output = (
        OUTPUT_DIR
        / "ten_pulsar_pair_correlations.csv"
    )

    ten_df.to_csv(
        ten_output,
        index=False,
    )

    print(
        "10-pulsar pairs:",
        len(ten_df)
    )

    print()
    print("Saved:")
    print(group_output)
    print(ten_output)


if __name__ == "__main__":
    main()