# -*- coding: utf-8 -*-
"""06_make_figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Create the project's main figures.

Figures:

1. Pulsar distribution
2. RMS reduction following whitening
3. Pairwise correlation distributions
4. Reduction in correlation scatter
5. Whitened correlations vs angular separation
6. Binned whitened correlations vs angular separation
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from config import OUTPUT_DIR


def hellings_downs(theta_deg):

    x = (
        1
        - np.cos(np.radians(theta_deg))
    ) / 2

    return (
        0.5
        - x / 4
        + 1.5 * x * np.log(x)
    )


# ---------------------------------------------------------
# Figure 1
# ---------------------------------------------------------

def figure_1():

    df = pd.read_csv(
        OUTPUT_DIR / "pulsar_positions.csv"
    )

    plt.figure(figsize=(12, 6))

    plt.scatter(
        df["ecliptic_longitude_deg"],
        df["ecliptic_latitude_deg"],
        s=40,
    )

    plt.xlabel(
        "Ecliptic longitude (degrees)"
    )

    plt.ylabel(
        "Ecliptic latitude (degrees)"
    )

    plt.title(
        "Distribution of the 68 Pulsars "
        "in the NANOGrav 15-year Dataset"
    )

    plt.xlim(0, 360)
    plt.ylim(-90, 90)

    plt.grid(alpha=0.25)
    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "Figure1_pulsar_distribution.png",
        dpi=200,
    )

    plt.close()


# ---------------------------------------------------------
# Figure 2
# ---------------------------------------------------------

def figure_2():

    df = pd.read_csv(
        OUTPUT_DIR / "rms_whitening_results.csv"
    )

    df = df.sort_values(
        "rms_reduction_percent"
    )

    plt.figure(figsize=(10, 9))

    plt.barh(
        df["pulsar"],
        df["rms_reduction_percent"],
    )

    plt.axvline(
        10,
        linestyle="--",
        linewidth=1,
    )

    plt.axvline(
        50,
        linestyle="--",
        linewidth=1,
    )

    plt.xlabel(
        "Percentage reduction in residual RMS (%)"
    )

    plt.ylabel("Pulsar")

    plt.title(
        "Percentage Reduction in Residual RMS "
        "Following Published Whitening"
    )

    plt.grid(
        axis="x",
        alpha=0.25,
    )

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "Figure2_RMS_reduction.png",
        dpi=200,
    )

    plt.close()


# ---------------------------------------------------------
# Figure 3
# ---------------------------------------------------------

def figure_3():

    df = pd.read_csv(
        OUTPUT_DIR / "selection_group_correlations.csv"
    )

    groups = [
        "Strong",
        "Moderate",
        "Weak",
    ]

    original = [
        df.loc[
            df["group"] == g,
            "original_correlation",
        ].values
        for g in groups
    ]

    whitened = [
        df.loc[
            df["group"] == g,
            "white_correlation",
        ].values
        for g in groups
    ]

    fig, ax = plt.subplots(
        figsize=(10, 6)
    )

    original_positions = [
        1, 4, 7
    ]

    whitened_positions = [
        2, 5, 8
    ]

    ax.boxplot(
        original,
        positions=original_positions,
        widths=0.6,
    )

    ax.boxplot(
        whitened,
        positions=whitened_positions,
        widths=0.6,
    )

    ax.axhline(
        0,
        linewidth=0.8,
    )

    ax.set_xticks(
        [1.5, 4.5, 7.5]
    )

    ax.set_xticklabels(groups)

    ax.set_xlabel(
        "Pulsar-selection group"
    )

    ax.set_ylabel(
        "Pairwise Pearson correlation"
    )

    ax.set_title(
        "Pairwise Correlations Before and "
        "After Whitening"
    )

    ax.grid(
        axis="y",
        alpha=0.25,
    )

    # Add simple labels above each pair.
    ax.text(
        1.0,
        ax.get_ylim()[1] * 0.95,
        "Original",
        ha="center",
    )

    ax.text(
        2.0,
        ax.get_ylim()[1] * 0.95,
        "Whitened",
        ha="center",
    )

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR
        / "Figure3_correlation_distributions.png",
        dpi=200,
    )

    plt.close()


# ---------------------------------------------------------
# Figure 4
# ---------------------------------------------------------

def figure_4():

    df = pd.read_csv(
        OUTPUT_DIR / "selection_group_correlations.csv"
    )

    rows = []

    for group in [
        "Strong",
        "Moderate",
        "Weak",
    ]:

        d = df[df["group"] == group]

        original_std = (
            d["original_correlation"].std()
        )

        whitened_std = (
            d["white_correlation"].std()
        )

        reduction = (
            100
            * (1 - whitened_std / original_std)
        )

        rows.append(
            {
                "group": group,
                "reduction": reduction,
            }
        )

    stats = pd.DataFrame(rows)

    plt.figure(figsize=(8, 6))

    plt.bar(
        stats["group"],
        stats["reduction"],
    )

    plt.ylabel(
        "Reduction in correlation scatter (%)"
    )

    plt.xlabel(
        "Pulsar-selection group"
    )

    plt.title(
        "Reduction in Pairwise Correlation Scatter "
        "Following Whitening"
    )

    plt.ylim(0, 100)

    plt.grid(
        axis="y",
        alpha=0.25,
    )

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "Figure4_scatter_reduction.png",
        dpi=200,
    )

    plt.close()


# ---------------------------------------------------------
# Figure 5
# ---------------------------------------------------------

def figure_5():

    df = pd.read_csv(
        OUTPUT_DIR / "ten_pulsar_pair_correlations.csv"
    )

    theta = np.linspace(
        0.01,
        180,
        500,
    )

    hd = hellings_downs(theta)

    plt.figure(figsize=(10, 6))

    plt.plot(
        theta,
        hd,
        linewidth=2,
        label="Hellings–Downs curve",
    )

    plt.scatter(
        df["separation_deg"],
        df["white_correlation"],
        s=45,
        alpha=0.75,
        label="Whitened pairwise correlations",
    )

    plt.axhline(
        0,
        linewidth=0.8,
    )

    plt.xlabel(
        "Pulsar angular separation (degrees)"
    )

    plt.ylabel(
        "Whitened Pearson correlation coefficient"
    )

    plt.title(
        "Whitened Pearson Correlation vs. "
        "Pulsar Angular Separation"
    )

    plt.xlim(0, 180)

    plt.grid(alpha=0.25)

    plt.legend()

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "Figure5_HD_correlation.png",
        dpi=200,
    )

    plt.close()


# ---------------------------------------------------------
# Figure 6
# ---------------------------------------------------------

def figure_6():

    df = pd.read_csv(
        OUTPUT_DIR / "ten_pulsar_pair_correlations.csv"
    )

    bins = np.arange(
        0,
        181,
        20,
    )

    df["bin"] = pd.cut(
        df["separation_deg"],
        bins=bins,
        include_lowest=True,
    )

    grouped = (
        df.groupby(
            "bin",
            observed=True,
        )["white_correlation"]
        .agg(
            ["mean", "std", "count"]
        )
    )

    midpoints = np.array(
        [
            interval.mid
            for interval in grouped.index
        ]
    )

    error = (
        grouped["std"]
        / np.sqrt(grouped["count"])
    )

    theta = np.linspace(
        0.01,
        180,
        500,
    )

    hd = hellings_downs(theta)

    plt.figure(figsize=(10, 6))

    plt.plot(
        theta,
        hd,
        linewidth=2,
        label="Hellings–Downs curve",
    )

    plt.errorbar(
        midpoints,
        grouped["mean"],
        yerr=error,
        fmt="o",
        markersize=7,
        capsize=4,
        label="Whitened correlations",
    )

    for x, y, n in zip(
        midpoints,
        grouped["mean"],
        grouped["count"],
    ):

        plt.annotate(
            f"N={int(n)}",
            (x, y),
            xytext=(0, 10),
            textcoords="offset points",
            ha="center",
            fontsize=9,
        )

    plt.axhline(
        0,
        linewidth=0.8,
    )

    plt.xlabel(
        "Pulsar angular separation (degrees)"
    )

    plt.ylabel(
        "Mean whitened Pearson correlation"
    )

    plt.title(
        "Mean Whitened Pairwise Correlation "
        "in 20° Angular-Separation Bins"
    )

    plt.xlim(0, 180)

    plt.grid(alpha=0.25)

    plt.legend()

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR
        / "Figure6_binned_correlations.png",
        dpi=200,
    )

    plt.close()


def main():

    figure_1()
    figure_2()
    figure_3()
    figure_4()
    figure_5()
    figure_6()

    print(
        "Figures 1–6 created successfully."
    )

    print(
        "Output directory:",
        OUTPUT_DIR,
    )


if __name__ == "__main__":
    main()