# -*- coding: utf-8 -*-
"""07_summary_statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Calculate the main numerical results for the project.
"""

import numpy as np
import pandas as pd

from config import OUTPUT_DIR


def hellings_downs(theta_deg):

    x = (
        1
        - np.cos(np.radians(theta_deg))
    ) / 2

    return (
        0.5
        - x / 4
        + 1.5 * x * np.log(x)
    )


def main():

    print()
    print("=" * 70)
    print("NANOGrav NOISE-MODELING PROJECT SUMMARY")
    print("=" * 70)

    # ---------------------------------------------
    # RMS analysis
    # ---------------------------------------------

    rms = pd.read_csv(
        OUTPUT_DIR / "rms_whitening_results.csv"
    )

    print()
    print("RMS ANALYSIS")
    print("-" * 40)

    print(
        "Pulsars with original + whitened products:",
        len(rms),
    )

    print(
        "Mean RMS reduction:",
        round(
            rms["rms_reduction_percent"].mean(),
            2,
        ),
        "%",
    )

    print(
        "Median RMS reduction:",
        round(
            rms["rms_reduction_percent"].median(),
            2,
        ),
        "%",
    )

    # ---------------------------------------------
    # Selection groups
    # ---------------------------------------------

    groups = pd.read_csv(
        OUTPUT_DIR / "pulsar_selection_groups.csv"
    )

    print()
    print("SELECTION GROUPS")
    print("-" * 40)

    print(
        groups["group"].value_counts()
    )

    # ---------------------------------------------
    # Pairwise correlations
    # ---------------------------------------------

    df = pd.read_csv(
        OUTPUT_DIR / "selection_group_correlations.csv"
    )

    print()
    print("CORRELATION ANALYSIS")
    print("-" * 40)

    for group in [
        "Strong",
        "Moderate",
        "Weak",
    ]:

        d = df[df["group"] == group]

        original_std = (
            d["original_correlation"].std()
        )

        white_std = (
            d["white_correlation"].std()
        )

        scatter_reduction = (
            100
            * (
                1
                - white_std
                / original_std
            )
        )

        x = (
            1
            - np.cos(
                np.radians(
                    d["separation_deg"]
                )
            )
        ) / 2

        hd = (
            0.5
            - x / 4
            + 1.5 * x * np.log(x)
        )

        agreement = np.corrcoef(
            d["white_correlation"],
            hd,
        )[0, 1]

        rms_difference = np.sqrt(
            np.mean(
                (
                    d["white_correlation"]
                    - hd
                ) ** 2
            )
        )

        print()
        print(group)
        print("Number of pairs:", len(d))
        print(
            "Mean whitened correlation:",
            round(
                d["white_correlation"].mean(),
                3,
            ),
        )
        print(
            "Whitened correlation scatter:",
            round(white_std, 3),
        )
        print(
            "Scatter reduction:",
            round(
                scatter_reduction,
                1,
            ),
            "%",
        )
        print(
            "Agreement with HD:",
            round(
                agreement,
                3,
            ),
        )
        print(
            "RMS difference from HD:",
            round(
                rms_difference,
                3,
            ),
        )

    # ---------------------------------------------
    # 10-pulsar analysis
    # ---------------------------------------------

    ten = pd.read_csv(
        OUTPUT_DIR
        / "ten_pulsar_pair_correlations.csv"
    )

    print()
    print("10-PULSAR ANALYSIS")
    print("-" * 40)

    print(
        "Number of pairs:",
        len(ten),
    )

    print(
        "Original correlation scatter:",
        round(
            ten["original_correlation"].std(),
            3,
        ),
    )

    print(
        "Whitened correlation scatter:",
        round(
            ten["white_correlation"].std(),
            3,
        ),
    )

    reduction = (
        100
        * (
            1
            - ten["white_correlation"].std()
            / ten["original_correlation"].std()
        )
    )

    print(
        "Scatter reduction:",
        round(reduction, 1),
        "%",
    )

    print()
    print("=" * 70)


if __name__ == "__main__":
    main()