# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzp5lDJpNG30yUTcb6hIdMT_vmGOelmt
"""

"""
Configuration for the NANOGrav 15-year noise-modeling project.
"""

from pathlib import Path

# Location of the downloaded NANOGrav 15-year dataset.
DATA_DIR = (
    Path.home()
    / "Downloads"
    / "NANOGrav15yr_PulsarTiming_v2.1.0"
)

# Dataset subdirectories.
RESIDUAL_DIR = DATA_DIR / "residuals"
PAR_DIR = (
    DATA_DIR
    / "narrowband"
    / "alternate"
    / "predictive"
)

# Output directory.
OUTPUT_DIR = Path.home() / "Downloads" / "NANOGrav_project_outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Analysis settings.
MAX_MATCH_DAYS = 10.0

# Exploratory pulsar-selection thresholds.
STRONG_THRESHOLD = 50.0
MODERATE_THRESHOLD = 10.0

# Pulsars used for the 10-pulsar exploratory analysis.
TEN_PULSARS = [
    "B1937+21",
    "J1745+1017",
    "J1903+0327",
    "J1946+3417",
    "J0613-0200",
    "J1909-3744",
    "J1643-1224",
    "J1713+0747",
    "J1744-1134",
    "J0437-4715",
]